#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7

services: postgresql

before_install:
#   - export DJANGO_SETTINGS_MODULE=pdk/settings
  - export PYTHONPATH=$HOME/builds/audaciouscode/pdk
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - django-admin.py startproject pdk
  - cd pdk
  - git clone https://github.com/audaciouscode/PassiveDataKit-Django.git
  - cp -R PassiveDataKit-Django passive_data_kit
  - cp passive_data_kit/test_settings.py ../pdk/settings.py
  - python manage.py migrate
  - python manage.py test

