dist: trusty

env:

language: python

python:
  - 2.7

service:
  - postgresql

addons:
  apt:
    packages:
    - spatialite-bin
  
before_install:
  - export PYTHONPATH=$HOME/builds/audaciouscode/pdk
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5 postgresql-9.5-postgis
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "CREATE DATABASE travisci;" 
  - psql -U postgres -c "CREATE EXTENSION postgis" -d travisci
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d travisci

script:
  - cd ..
  - mv PassiveDataKit-Django passive_data_kit
  - mkdir django
  - cd django
  - django-admin.py startproject pdk
  - mv ../passive_data_kit pdk
  - cd pdk
  - cp passive_data_kit/travis_settings.py pdk/settings.py
  - python manage.py migrate
  - python manage.py test
  - cp passive_data_kit/.pylintrc .
  - pylint passive_data_kit
  - bandit -r .
