language: python

python:
  - 2.7

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
  
before_install:
  - export PYTHONPATH=$HOME/builds/audaciouscode/pdk
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - psql -U postgres -c "CREATE EXTENSION postgis" -d travisci
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d travisci

script:
  - django-admin.py startproject pdk
  - cd pdk
  - git clone https://github.com/audaciouscode/PassiveDataKit-Django.git
  - cp -R PassiveDataKit-Django passive_data_kit
  - cp passive_data_kit/travis_settings.py pdk/settings.py
  - python manage.py migrate
  - python manage.py test

